version: '1.0'

services:
  backend:
    build: ./backend
    ports:
      - "8000:8000"  
    depends_on:
      - database

  frontend:
    build: ./frontend
    ports:
      - "80:6000"  

  database:
    build: ./database
    ports:
      - "5432:5432"
    volumes:
      - my-database-volume:/var/lib/postgresql/data

volumes:
  my-database-volume: