version: '1.0'

services:
  backend:
    build: ./backend
    networks:
      - internal-network

  frontend:
    build: ./frontend
    ports:
      - "80:80"
    networks:
      - internal-network

  database:
    build: ./database
    #volumes:
    #  - my-database-volume:/var/lib/postgresql/data
    networks:
      - internal-network

volumes:
  my-database-volume:

networks:
  internal-network:
