# Use the official PostgreSQL image as a base
FROM postgres:latest

# Set environment variables for PostgreSQL
ENV POSTGRES_USER="backend_user"
ENV POSTGRES_PASSWORD="password"
ENV POSTGRES_DB="Makers-Lab-DB"

# Expose PostgreSQL port
EXPOSE 5432

#psql -U backend_user Makers-Lab-DB
#psql -U backend_user Makers-Lab-DB -a -f /home/a.txt